import json
from pathlib import Path
from datetime import datetime

# ==========================================================
# JSON CONFIG GENERATOR FOR EEG FEATURE EXTRACTION PIPELINE
# ==========================================================
# This script creates a JSON configuration file for the EEG
# feature extraction pipeline.
#
# This step depends on the previous WINDOWING + LABELING step.
#
# The user defines:
# - path to the previous labeling JSON config
# - output root folder for feature extraction results
# - config output folder
# - feature extraction options
# - version
#
# The script automatically reads from the previous labeling config:
# - patient_id
# - labeling experiment_id
# - input_npz_dir
# - df_labeled_path
# - df_final_path
# - windowing parameters
# - labeling parameters
#
# The script automatically generates:
# - feature_extraction_id
# - output folder
# - output filenames
# - config filename
#
# Output names depend on:
# - previous labeling experiment_id
# - selected feature groups
# - date
# - version
# ==========================================================


# ==========================================================
# HELPER FUNCTIONS
# ==========================================================

def load_json_config(config_path):
    """
    Load a JSON configuration file.
    """

    config_path = Path(config_path)

    if not config_path.exists():
        raise FileNotFoundError(f"Config file not found: {config_path}")

    with open(config_path, "r") as f:
        config = json.load(f)

    return config


def clean_text_for_name(text):
    """
    Convert text into a filename-safe string.

    Example:
    'time_domain + frequency_domain' -> 'timedomain-frequencydomain'
    """

    text = str(text)
    text = text.replace(" ", "")
    text = text.replace("+", "-")
    text = text.replace("/", "-")
    text = text.replace(".", "")
    text = text.replace("_", "")
    return text


def build_feature_code(feature_extraction):
    """
    Build a compact code describing which feature groups are enabled.

    Example:
    time + freq -> TIME-FREQ
    """

    codes = []

    if feature_extraction["extract_time_domain_features"]:
        codes.append("TIME")

    if feature_extraction["extract_frequency_domain_features"]:
        codes.append("FREQ")

    if feature_extraction["extract_entropy_features"]:
        codes.append("ENTROPY")

    if feature_extraction["extract_connectivity_features"]:
        codes.append("CONN")

    if len(codes) == 0:
        codes.append("NOFEATURES")

    return "-".join(codes)


def build_feature_extraction_id(
    labeling_experiment_id,
    feature_extraction,
    date_code,
    version
):
    """
    Build a reproducible feature extraction ID based on:
    - previous labeling experiment ID
    - selected feature groups
    - date
    - version
    """

    feature_code = build_feature_code(feature_extraction)

    feature_extraction_id = (
        f"{labeling_experiment_id}_"
        f"FEAT-{feature_code}_"
        f"{date_code}_"
        f"{version}"
    )

    return feature_extraction_id


def get_previous_output_paths(labeling_config):
    """
    Extract output paths from the previous labeling config.
    """

    output_paths = labeling_config.get("output_paths", {})

    df_labeled_path = output_paths.get("df_labeled_path")
    df_final_path = output_paths.get("df_final_path")

    if df_labeled_path is None:
        raise KeyError("Missing output_paths['df_labeled_path'] in previous labeling config.")

    if df_final_path is None:
        raise KeyError("Missing output_paths['df_final_path'] in previous labeling config.")

    return df_labeled_path, df_final_path


# ==========================================================
# CONFIG CREATION FUNCTION
# ==========================================================

def create_feature_extraction_config():

    # ======================================================
    # USER EDIT SECTION
    # ======================================================
    # Edit only this section before running the script.
    #
    # previous_labeling_config_path:
    #   Path to the JSON config generated by the previous
    #   windowing + labeling step.
    #
    # output_root_dir:
    #   Folder where the feature extraction experiment folder
    #   will be created.
    #
    # config_output_dir:
    #   Folder where this new feature extraction JSON config
    #   will be saved.
    #
    # version:
    #   Version of this feature extraction config.
    #
    # feature_extraction:
    #   Controls which feature groups will be extracted.
    # ======================================================

    # ------------------------------------------------------
    # PREVIOUS LABELING CONFIG
    # ------------------------------------------------------
    previous_labeling_config_path = (
        "/home/tperezsanchez/FoundationModel_EEG_Dissertation/"
        "Main_project/src/pipelines/2_Feature_ext/configs/"
        "config_JYXFE_IN-normalized_npz_FP-fullnpz_W10s_PRE8to5min_ICT0to3min_GAPasINT_FINAL-PREvsSEIZ_20260519_v01.json"
    )

    # ------------------------------------------------------
    # OUTPUT ROOT FOLDER
    # ------------------------------------------------------
    output_root_dir = (
        "/home/tperezsanchez/FoundationModel_EEG_Dissertation/"
        "Main_project/results/JYXFE/Feature_ext/Part2_features"
    )

    # ------------------------------------------------------
    # CONFIG OUTPUT FOLDER
    # ------------------------------------------------------
    config_output_dir = (
        "/home/tperezsanchez/FoundationModel_EEG_Dissertation/"
        "Main_project/src/pipelines/2_Feature_ext/configs"
    )

    # ------------------------------------------------------
    # VERSION
    # ------------------------------------------------------
    version = "v01"

    # ------------------------------------------------------
    # FEATURE EXTRACTION PARAMETERS
    # ------------------------------------------------------
    feature_extraction = {
        # Whether to extract features from all labeled windows
        "extract_features_all_windows": True,

        # Whether to extract features only from final filtered dataframe
        # Usually this is preictal vs seizure.
        "extract_features_final": True,

        # Feature groups
        "extract_time_domain_features": True,
        "extract_frequency_domain_features": True,

        # Optional future feature groups
        "extract_entropy_features": False,
        "extract_connectivity_features": False,

        # Whether to use file cache when loading NPZ files
        "use_file_cache": True,

        # Whether np.load should allow pickle objects
        "allow_pickle": True
    }

    # ------------------------------------------------------
    # FEATURE PARAMETERS
    # ------------------------------------------------------
    feature_parameters = {
        # Frequency bands used for band power features
        "frequency_bands": {
            "delta": [0.5, 4.0],
            "theta": [4.0, 8.0],
            "alpha": [8.0, 13.0],
            "beta": [13.0, 30.0],
            "gamma": [30.0, 40.0]
        },

        # Welch PSD parameters.
        # If nperseg is None, the feature extraction pipeline
        # can choose a sensible default.
        "welch": {
            "nperseg": None,
            "noverlap": None
        },

        # Optional entropy settings
        "sample_entropy": {
            "m": 2,
            "r": 0.2
        }
    }

    # ------------------------------------------------------
    # PIPELINE STEPS
    # ------------------------------------------------------
    pipeline_steps = {
        "load_previous_labeling_config": True,
        "load_input_pickles": True,
        "load_npz_files": True,
    
        # Required by the current feature extraction pipeline
        "run_features_ictalVspreictal": True,
        "run_features_all": True,
        "save_outputs": True,
    
        # Optional metadata / future use
        "save_feature_summary": True
    }

    # ======================================================
    # LOAD PREVIOUS LABELING CONFIG
    # ======================================================

    labeling_config = load_json_config(previous_labeling_config_path)

    labeling_experiment_id = labeling_config["experiment_id"]
    patient_id = labeling_config["patient_id"]

    input_npz_dir = labeling_config["paths"]["input_npz_dir"]

    df_labeled_path, df_final_path = get_previous_output_paths(labeling_config)

    # ======================================================
    # AUTOMATIC NAMING
    # ======================================================

    date_code = datetime.now().strftime("%Y%m%d")
    created_at = datetime.now().isoformat(timespec="seconds")

    feature_extraction_id = build_feature_extraction_id(
        labeling_experiment_id=labeling_experiment_id,
        feature_extraction=feature_extraction,
        date_code=date_code,
        version=version
    )

    # Main experiment output folder
    output_dir = Path(output_root_dir) / feature_extraction_id
    output_dir.mkdir(parents=True, exist_ok=True)

    # Automatically generated output filenames
    df_features_all_filename = f"{feature_extraction_id}_df_features_all.pkl"

    df_features_ictalVspreictal_filename = (
        f"{feature_extraction_id}_df_features_ictalVspreictal.pkl"
    )
    
    feature_summary_filename = f"{feature_extraction_id}_feature_summary.csv"

    # Full output paths
    df_features_all_path = output_dir / df_features_all_filename
    
    df_features_ictalVspreictal_path = (
        output_dir / df_features_ictalVspreictal_filename
    )
    
    feature_summary_path = output_dir / feature_summary_filename
    # ======================================================
    # INPUT FILES
    # ======================================================

    input_files = {
        "df_labeled_all": Path(df_labeled_path).name,
        "df_ictalVspreictal": Path(df_final_path).name
    }

    input_paths = {
        "df_labeled_all_path": str(df_labeled_path),
        "df_ictalVspreictal_path": str(df_final_path)
    }

    # ======================================================
    # CONFIG DICTIONARY
    # ======================================================

    config = {
        # --------------------------------------------------
        # EXPERIMENT INFORMATION
        # --------------------------------------------------
        "feature_extraction_id": feature_extraction_id,
        "labeling_experiment_id": labeling_experiment_id,
        "created_at": created_at,
        "date_code": date_code,
        "version": version,

        # --------------------------------------------------
        # PATIENT INFORMATION
        # --------------------------------------------------
        "patient_id": patient_id,

        # --------------------------------------------------
        # PREVIOUS CONFIG
        # --------------------------------------------------
        "previous_step": {
            "step_name": "windowing_labeling",
            "previous_labeling_config_path": str(previous_labeling_config_path),
            "labeling_experiment_id": labeling_experiment_id
        },

        # --------------------------------------------------
        # FILE AND FOLDER PATHS
        # --------------------------------------------------
        "paths": {
            # Folder containing normalized .npz files
            "input_npz_dir": str(input_npz_dir),

            # Folder containing labeled pickle files
            "input_pickle_dir": str(Path(df_labeled_path).parent),

            # User-defined root output folder
            "output_root_dir": str(output_root_dir),

            # Automatically generated output folder
            "output_dir": str(output_dir)
        },

        # --------------------------------------------------
        # INPUT FILES
        # --------------------------------------------------
        "input_files": input_files,

        # --------------------------------------------------
        # FULL INPUT PATHS
        # --------------------------------------------------
        "input_paths": input_paths,

        # --------------------------------------------------
        # PREVIOUS WINDOWING PARAMETERS
        # --------------------------------------------------
        # Useful for traceability.
        "windowing": labeling_config.get("windowing", {}),

        # --------------------------------------------------
        # PREVIOUS LABELING PARAMETERS
        # --------------------------------------------------
        # Useful for traceability.
        "labeling": labeling_config.get("labeling", {}),

        # --------------------------------------------------
        # PREVIOUS FILTERING PARAMETERS
        # --------------------------------------------------
        # Useful for traceability.
        "filtering": labeling_config.get("filtering", {}),

        # --------------------------------------------------
        # FEATURE EXTRACTION PARAMETERS
        # --------------------------------------------------
        "feature_extraction": feature_extraction,

        # --------------------------------------------------
        # FEATURE PARAMETERS
        # --------------------------------------------------
        "feature_parameters": feature_parameters,

        # --------------------------------------------------
        # OUTPUT FILES
        # --------------------------------------------------
        "output_files": {
            # Required by the current feature extraction pipeline
            "df_features_all": df_features_all_filename,
            "df_features_ictalVspreictal": df_features_ictalVspreictal_filename,
        
            # Optional aliases for readability
            "df_features_all_filename": df_features_all_filename,
            "df_features_ictalVspreictal_filename": df_features_ictalVspreictal_filename,
            "feature_summary_filename": feature_summary_filename
        },

        # --------------------------------------------------
        # FULL OUTPUT PATHS
        # --------------------------------------------------
        "output_paths": {
            "df_features_all_path": str(df_features_all_path),
            "df_features_ictalVspreictal_path": str(df_features_ictalVspreictal_path),
        
            # Optional alias
            "feature_summary_path": str(feature_summary_path)
        },
        # --------------------------------------------------
        # AUTOMATIC NAMING INFORMATION
        # --------------------------------------------------
        "naming": {
            "labeling_experiment_id": labeling_experiment_id,
            "feature_code": build_feature_code(feature_extraction),
            "date_code": date_code,
            "version": version
        },

        # --------------------------------------------------
        # PIPELINE STEPS
        # --------------------------------------------------
        "pipeline_steps": pipeline_steps
    }

    # ======================================================
    # SAVE JSON FILE
    # ======================================================

    config_output_dir = Path(config_output_dir)
    config_output_dir.mkdir(parents=True, exist_ok=True)

    config_path = config_output_dir / f"config_{feature_extraction_id}.json"

    with open(config_path, "w") as f:
        json.dump(config, f, indent=4)

    # ======================================================
    # PRINT SUMMARY
    # ======================================================

    print("Feature extraction config saved at:")
    print(config_path.resolve())

    print("\nPrevious labeling experiment ID:")
    print(labeling_experiment_id)

    print("\nFeature extraction ID:")
    print(feature_extraction_id)

    print("\nInput files:")
    print(df_labeled_path)
    print(df_final_path)

    print("\nFeature extraction output directory:")
    print(output_dir.resolve())

    print("\nGenerated output files:")
    print(df_features_all_path)
    print(df_features_ictalVspreictal_path)
    print(feature_summary_path)

    return config


# ==========================================================
# RUN SCRIPT
# ==========================================================

if __name__ == "__main__":
    create_feature_extraction_config()


# ==========================================================
# HOW TO RUN
# ==========================================================
# 1. Generate the JSON config:
# python create_config_feature_extraction.py
#
# 2. Run the feature extraction pipeline with the generated config:
# python 2_2_Feature_ext_features.py configs/config_<feature_extraction_id>.json
# ==========================================================